# Generated by Django 2.2.16 on 2022-05-26 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngredient', to='recipes.Ingredient', validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Ингредиенты'),
        ),
    ]
