# Generated by Django 2.2.16 on 2022-05-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220502_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Подписки'},
        ),
    ]
